// Code generated by MockGen. DO NOT EDIT.
// Source: processor/core/requester/requester.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "processor/payment/models"
	reflect "reflect"
)

// MockRequester is a mock of Requester interface
type MockRequester struct {
	ctrl     *gomock.Controller
	recorder *MockRequesterMockRecorder
}

// MockRequesterMockRecorder is the mock recorder for MockRequester
type MockRequesterMockRecorder struct {
	mock *MockRequester
}

// NewMockRequester creates a new mock instance
func NewMockRequester(ctrl *gomock.Controller) *MockRequester {
	mock := &MockRequester{ctrl: ctrl}
	mock.recorder = &MockRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRequester) EXPECT() *MockRequesterMockRecorder {
	return m.recorder
}

// SendBuyRequest mocks base method
func (m *MockRequester) SendBuyRequest(process models.Process, card models.CardData, acquirerURL string, errors *models.Error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBuyRequest", process, card, acquirerURL, errors)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SendBuyRequest indicates an expected call of SendBuyRequest
func (mr *MockRequesterMockRecorder) SendBuyRequest(process, card, acquirerURL, errors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBuyRequest", reflect.TypeOf((*MockRequester)(nil).SendBuyRequest), process, card, acquirerURL, errors)
}
